### ISSUE TITLE
Инструкции по сборке

### ISSUE THREAD

**Issue by TitaniumHocker** [facilisdes/sqt#1]
Штука конешн интересная, только не собирается, какие-то зависимости просит.
Хоть бы написал, что поставить нужно помимо самого компилятора и т.д.

**Comment by facilisdes** [comment]
Ещё интереснее было бы узнать, зачем кому-то понадобилось собирать эту штуку, которая делалась для проверки одного конкретного задания на одном конкретном турнире. 
Да и в принципе увидеть список этих каких-то зависимостей - в былые времена оно собиралось на разных устройствах и даже под разными операционками без намёков на проблемы.

**Comment by TitaniumHocker** [comment]
Чисто гулял по гитхабу и увидел README на русском, как же не собрать после такого. Вообще он ругался, что не может импортировать пакеты которые в самой репе, пришлось положить копию в ~/go/src и вроде все собралось, хотя я все же не очень понял что это и зачем, и зачем обфусцировать конфиг?

**Comment by facilisdes** [comment]
Да я уже и сам не помню. Вроде бы это было задание на симуляцию обработки конкурентных операций, а конфиг шифруется чтобы сервер (тут отдельная путаница в понятиях, с точки зрения инфраструктуры в целом серверов много, а клиент один - клиент запрашивает у серверов данные и фиксирует время ответа), а точнее ответственный за него человек, не мог подкрутить параметры симуляции очереди - а то выставил бы себе время нахождения в очереди поменьше и даже на более тормозном конфиге оказался бы с более высокими показателями. Но это я только предполагаю, точно не помню, а может и изначально не знал.
